
[[_Usage]]
= Usage

The following sections describe how you may use this plugin in an project.

== Configuration

You must create a configuration file named `Db4o` that holds the settings for creating instances of `com.db4o.ObjectContainer`.
This file follows the same standard configuration mechanism as the application's `Config` file, which means you can define the
configuration using

 * a properties file
 * a Java file
 * a Groovy script

The following example shows the default settings needed to connect the default datasource taking into account that each
environment may connect to a different datasource.

[source,groovy,options="nowrap"]
.src/main/resources/Db4o.groovy
----
include::{path_griffon_db4o_core}/src/test/resources/Db4o.groovy[lines=16..36]
----

You may configure multiple named datasources (the default factory is aptly named `default`) as the following snippet
shows

[source,groovy,options="nowrap"]
.src/main/resources/Db4o.groovy
----
include::{path_griffon_db4o_core}/src/test/resources/Db4o.groovy[lines=38..45]
----

The following properties are optional

[cols="4*",options="header"]
|===
| Property           | Type    | Default | Description
| delete             | boolean | false   | Deletes the datasource file when disconnectingfrom the datasource.
| connect_on_startup | boolean | false   | Establishes a connection to the datasource at the beginning of the `Startup` phase.
|===

The plugin's <<_modules, module>> registers a `{api_object_container_handler}` helper class that defines the base contract
for accessing a datasource and issue queries to it. This class has the following methods

[source,java,options="nowrap"]
.griffon.plugins.db4o.ObjectContainerHandler.java
----
include::{path_griffon_db4o_core}/src/main/java//griffon/plugins/db4o/ObjectContainerHandler.java[tags=methods,indent=0]
----

These method are aware of multiple datasources. If no dataSourceName is specified when calling them then the default
datasource will be selected. You can inject an instance of this class anywhere it's needed using `@Inject`. There is one
callback you may use with this method: `{api_object_container_callback}`.

This callback is defined using a functional interface approach, which means you can apply lambda expressions if running
with JDK8+ or closures if running Groovy.

[source,java,options="nowrap"]
.griffon.plugins.db4o.ObjectContainerCallback.java
----
include::{path_griffon_db4o_core}/src/main/java/griffon/plugins/db4o/ObjectContainerCallback.java[lines=26..-1]
----

=== Bootstrap

You may execute arbitrary datasource calls during connection and disconnection from a `com.db4o.ObjectContainer`. Simply
create a class that implements the `{api_db4o_bootstrap}` interface and register it within a module, for example

[source,java,options="nowrap"]
.src/main/java/com/acme/SampleDb4oBootstrap.java
----
package com.acme;

import griffon.plugins.db4o.Db4oBootstrap;
import com.db4o.ObjectContainer;

import javax.annotation.Nonnull;
import javax.inject.Named;

@Named("sample")
public class SampleDb4oBootstrap implements Db4oBootstrap {
    @Override
    public void init(@Nonnull String dataSourceName, @Nonnull ObjectContainer objectContainer) {
        // operations after first connection to objectContainer
    }

    @Override
    public void destroy(@Nonnull String dataSourceName, @Nonnull ObjectContainer objectContainer) {
        // operations before disconnecting from the objectContainer
    }
}
----

[source,java,options="nowrap"]
.src/main/java/com/acme/ApplicationModule.java
----
package com.acme;

import griffon.plugins.db4o.Db4oBootstrap;
import griffon.core.injection.Module;
import org.codehaus.griffon.runtime.core.injection.AbstractModule;
import org.kordamp.jipsy.ServiceProviderFor;

@ServiceProviderFor(Module.class)
public class ApplicationModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        bind(Db4oBootstrap.class)
            .to(SampleDb4oBootstrap.class)
            .asSingleton();
    }
}
----

== Example

The following is a trivial usage of the `{api_object_container_handler}` inside a Java service

[source,java,options="nowrap"]
.com.acme.SampleService.java
----
package com.acme;

import griffon.core.artifact.GriffonService;
import griffon.metadata.ArtifactProviderFor;
import org.codehaus.griffon.runtime.core.artifact.AbstractGriffonService;

import griffon.plugins.db4o.ObjectContainerHandler;
import griffon.plugins.db4o.ObjectContainerCallback;
import com.db4o.ObjectContainer;

import javax.annotation.Nonnull;
import javax.inject.Inject;

@ArtifactProviderFor(GriffonService.class)
public class SampleService extends AbstractGriffonService {
    @Inject
    private ObjectContainerHandler objectContainerHandler;

    public String getPersonName(final int id) {
         return objectContainerHandler.withDb4o(new ObjectContainerCallback<String>() {
             public String handle(@Nonnull String dataSourceName, @Nonnull ObjectContainer objectContainer) {
                 ...
         });
    }
}
----

Here's the Groovy version of it

[source,groovy,options="nowrap"]
.com.acme.SampleService.groovy
----
package com.acme

import griffon.core.artifact.GriffonService
import griffon.metadata.ArtifactProviderFor

import griffon.plugins.db4o.ObjectContainerHandler

import javax.inject.Inject

@ArtifactProviderFor(GriffonService)
class SampleService {
    @Inject
    private ObjectContainerHandler objectContainerHandler

    String getPersonName(int id) {
         objectContainerHandler.withDb4o { String dataSourceName, ObjectContainer objectContainer ->
             ...
         }
    }
}
----

== Events

The following events will be triggered by `{api_object_container_handler}`

Db4oConnectStart(String dataSourceName, Map<String, Object> config):: Triggered before connecting to the datasource.
Db4oConfigurationSetup(String dataSourceName, Map<String, Object> config, EmbeddedConfiguration configuration):: Triggered when configuring the object container
Db4oConnectEnd(String dataSourceName, Map<String, Object> config, ObjectContainer objectContainer):: Triggered after connecting to the datasource.
Db4oDisconnectStart(String dataSourceName, Map<String, Object> config, ObjectContainer objectContainer):: Triggered before disconnecting from the datasource.
Db4oDisconnectEnd(String dataSourceName, Map<String, Object> config):: Triggered after disconnecting from the datasource.

NOTE: DataSource events may be triggered during connection and disconnection from a `com.db4o.ObjectContainer`.

== AST Transformation

You can apply the `{api_db4o_aware}` AST transformation on any class. This injects the behavior of `{api_object_container_handler}`
into said class. The previous Groovy service example can be rewritten as follows

[source,groovy,options="nowrap"]
.com.acme.SampleService.groovy
----
package com.acme

import griffon.core.artifact.GriffonService
import griffon.metadata.ArtifactProviderFor
import griffon.transform.Db4oAware

import com.db4o.ObjectContainer

@Db4oAware
@ArtifactProviderFor(GriffonService)
class SampleService {
    String getPersonName(int id) {
         withDb4o { String dataSourceName, ObjectContainer objectContainer ->
             ...
         }
    }
}
----

== DSL Descriptors

This plugin provides DSL descriptors for Intellij IDEA and Eclipse (provided you have the Groovy Eclipse plugin installed).
These descriptors are found inside the `griffon-db4o-groovy-compile-{project-version}.jar`, with locations

 * dsdl/griffon_db4o.dsld
 * gdsl/griffon_db4o.gdsl
